In [1]:
import numpy as np

In [2]:
print('graph A')
print("1 -- 2    3")

graph A
1 -- 2    3


In [3]:
print('graph B')
print("1    2 -- 3")

graph B
1    2 -- 3


In [4]:
A = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 0]])
A

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [5]:
B = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0]])
B

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [6]:
P = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])

In [7]:
P

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [8]:
A_prime = np.dot(A, P)
A_prime

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [9]:
B_prime = np.dot(P, B)
B_prime

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [10]:
A_prime - B_prime

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])